# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/srinivas-byte/yuniql_doc $(Build.SourcesDirectory)\yuniql_doc'
- task: UseYuniqlCLI@1
  inputs:
    version: 'v1.1.55'


- task: RunYuniqlCLI@1
  inputs:
    version: 'v1.1.55'
    connectionString: 'postgres://ezvbafiw:XiBCzoqU0_4MTvd825eLwEfwcL4uWNiG@john.db.elephantsql.com:5432/ezvbafiw'
    workspacePath: '$(Build.SourcesDirectory)\yuniql_doc\basic-postgresql-sample'
    targetPlatform: 'postgresql'
    targetVersion: 'v1.1.55'
    additionalArguments: '--debug'

